name: Bundlewatch

on: [pull_request]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@v2.1.0
      - run: yarn install
      - uses: jackyef/bundlewatch-gh-action@master
        with:
          build-script: yarn build-ci
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
