name: Bundlewatch
on: [pull_request]

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    env:
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Use Node.js
        uses: actions/setup-node@v2.0.0
        with:
          node-version: 12.x

      - run: |
          npm i
          npm run build-ci
          npm run bundlewatch